image: docker:19.03

before_script:
  - apk update && apk add bash openssh sshpass

build:
  stage: build
  script:
    GIT_COMMIT_SHORT=$CI_COMMIT_SHORT_SHA GIT_BRANCH_SHORT=$CI_COMMIT_REF_NAME ./docker/dockerize.sh build && GIT_COMMIT_SHORT=$CI_COMMIT_SHORT_SHA GIT_BRANCH_SHORT=$CI_COMMIT_REF_NAME ./docker/dockerize.sh push
  only:
  - master
  - dev

deploy:
  stage: deploy
  script:
    GIT_COMMIT_SHORT=$CI_COMMIT_SHORT_SHA GIT_BRANCH_SHORT=$CI_COMMIT_REF_NAME ./docker/dockerize.sh update_dev
  only:
    - dev
