### LOGIN USER with taking TOKEN
POST http://localhost:8080/auth/login/
Content-Type: application/json
//{"username": "admin", "password": "pwd"}

{"email": "admin", "password": "pwd"}

> {% client.global.set("auth_token", response.body.token); %}

### GET USER INFO FOR USE IN FRONT
GET http://localhost:8080/auth/account_info
Authorization: Token {{auth_token}}

### operators grouped by profiles
GET http://localhost:8080/api/v1/operator/grouped/
Authorization: Token {{auth_token}}

### DONE - WIP: possible all fields need truncate
GET http://localhost:8080/api/v1/technical-capabilities/2419/
http://localhost:4200/api/v1/technical-capabilities/2419/
Authorization: Token {{auth_token}}


//********************** TODO: THIS WHAT I NEED FOR REDO ********************************************************

###
GET http://localhost:8080/api/v1/organization?location=11
#GET http://localhost:8080/api/v1/organization?location=2419
Authorization: Token {{auth_token}}