version: '2'
services:
  db:
    image: mdillon/postgis:11-alpine
    container_name: telecom-it-ng.db
    hostname: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 15432:5432
    env_file:
      - .env.telecom-it
#    restart: always

  redis:
    image: redis:4.0-alpine
    container_name: telecom-it-ng.redis
    hostname: redis
    ports:
      - 6379:6379
    env_file:
      - .env.telecom-it
#    restart: always

  backend:
    image: harbor.cifra-k.ru/telecom-it/telecom-backend-ng_feature/esia:latest
    container_name: telecom-it-ng.backend
    hostname: backend
    #    ports:
    #      - 8080:8080
    depends_on:
      - db
      - redis
    volumes:
      #      - ./data/media:/opt/media
      #      - ./data/static:/opt/static_files
      - ./data/certs:/opt/certs
    #      - ./data/application.properties:/app/application.properties
      - ./data/logs:/app/logs
    env_file:
      - .env.telecom-it
#    restart: always

  esia-service:
    image: harbor.cifra-k.ru/common/esia-service_master:latest
    container_name: telecom-it-ng.esia-service
    hostname: esia-service
    #    ports:
    #      - 8080:8080
    volumes:
      - ./data/certs:/app/data/certs
    env_file:
      - .env.telecom-it
#    restart: always

  frontend:
    image: harbor.cifra-k.ru/telecom-it/telecom-frontend_dev:latest
    container_name: telecom-it-ng.frontend
    hostname: frontend
    depends_on:
      - backend
    env_file:
      - .env.telecom-it
#    restart: always

  entry:
    image: nginx:1.17
    container_name: telecom-it-ng.entry
    hostname: entry
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/media:/var/www/media
      - ./data/static:/var/www/static
    ports:
      - 80:80
    env_file:
      - .env.telecom-it
#    restart: always
