version: '2'
services:
  db:
    image: mdillon/postgis:11-alpine
    container_name: telecom-ng.db
    hostname: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env.telecom-it
#    restart: always

  redis:
    image: redis:4.0-alpine
    container_name: telecom-ng.redis
    hostname: redis
    ports:
      - 6379:6379
    env_file:
      - .env.telecom-it
#    restart: always
