###
POST http://espd-utm5-app.cifra-k.ru:9080/api/login
Content-Type: application/json

{
    "username": "init",
    "password": "init"
}

> {% client.global.set("session_id", response.body.session_id); %}

###
GET http://espd-utm5-app.cifra-k.ru:9080/api/users/servicelinks/iptraffic?slink_id=3
Authorization: session_id {{session_id}}

###
GET http://espd-utm5-app.cifra-k.ru:9080/api/users/
Authorization: session_id {{session_id}}

###
GET http://espd-utm5-app.cifra-k.ru:9080/api/users/tarifflinks?user_id=94&account_id=95
Authorization: session_id {{session_id}}

###
GET http://espd-utm5-app.cifra-k.ru:9080/api/users/accounts?account_id=1
Authorization: session_id {{session_id}}

###
GET http://espd-utm5-app.cifra-k.ru:9080/api/users/?user_id=2
Authorization: session_id {{session_id}}


### ---------------------------------------------------------------------------
POST http://espd-utm5-app.cifra-k.ru:9080/api/users/
Content-Type: application/json

{
  "login" : "telecomit-2340",
  "password" : "qaz12345678",
  "full_name" : "2552 (24-й квартал,  2)",
  "is_juridical" : false,
  "juridical_address" : "",
  "actual_addres" : "",
  "flat_numbe" : "",
  "entranc" : "",
  "floo" : "",
  "distric" : "",
  "buildin" : "",
  "passpor" : "",
  "house_id" : 0,
  "work_telephon" : "",
  "home_telephon" : "",
  "mobile_telephon" : "",
  "web_pag" : "",
  "icq_numbe" : "",
  "tax_numbe" : "",
  "kpp_numbe" : "",
  "emai" : "",
  "bank_id" : 0,
  "bank_accoun" : "",
  "comment" : "",
  "personal_manage" : "",
  "connect_date" : 0,
  "is_send_invoice" : false,
  "advance_payment" : 0,
  "router_id" : 0,
  "port_number" : 0,
  "binded_currency_id" : 0,
  "additional_params" : [ ],
  "groups" : [ ],
  "is_blocked" : false,
  "balance" : 0,
  "credit" : 0,
  "vat_rate" : 0,
  "sale_tax_rate" : 0,
  "int_status" : 0
}

###

{"login": "foo-test-1",
  "password": "foo",
  "full_name": "foo-test-1",
  "is_juridical": false,
  "juridical_address": "",
  "actual_address": "",
  "flat_number": "",
  "entrance": "",
  "floor": "",
  "district": "",
  "building": "",
  "passport": "",
  "house_id": 0,
  "work_telephone": "",
  "home_telephone": "",
  "mobile_telephone": "",
  "web_page": "",
  "icq_number": "",
  "tax_number": "",
  "kpp_number": "",
  "email": "",
  "bank_id": 0,
  "bank_account": "",
  "comments": "",
  "personal_manager": "",
  "connect_date": 0,
  "is_send_invoice": false,
  "advance_payment": 0,
  "router_id": 0,
  "port_number": 0,
  "binded_currency_id": 0,
  "additional_params": [],
  "groups": [],
  "is_blocked": false,
  "balance": 0,
  "credit": 0,
  "vat_rate": 0,
  "sale_tax_rate": 0,
  "int_status": 0
}


### ---- Get all user service links
GET http://espd-utm5-app.cifra-k.ru:9080/api/users/servicelinks?user_id=7
Content-Type: application/json



### ---- Get ip groups or something
GET http://espd-utm5-app.cifra-k.ru:9080/api/users/ip_groups?account_id=7
#GET http://espd-utm5-app.cifra-k.ru:9080/api/referencebooks/ip_zones
Content-Type: application/json



### ---- Get ip Get iptraffic
GET http://espd-utm5-app.cifra-k.ru:9080/api/users/servicelinks/iptraffic?slink_id=7
Content-Type: application/json


#########################################
### ---- вот чему за сегодня я должен научиться!!!!!!!!!!!!!!!!!
## User/ServiceLinks - Post iptraffic
POST http://espd-utm5-app.cifra-k.ru:9080/api/users/servicelinks/iptraffic
Content-Type: application/json

{
  "user_id": 1,
  "account_id": 1,
  "service_id": 1,
  "tplink_id": 0,
  "accounting_period_id": 1,
  "start_date": 0,
  "expire_date": 0,
  "policy_id": 1,
  "cost_coef": 1,
  "house_comment": "",
  "comment": "",
  "unabon": 0,
  "house_id": 0,
  "unprepay": 0,
  "ip_group": [
    {
      "ip": "0.0.0.0",
      "mask": 32,
      "mac": "",
      "login": "",
      "allowed_cid": "",
      "password": "",
      "pool_name": "",
      "flags": 0,
      "nfprovider_id": 0,
      "switch_id": 0,
      "port_id": 0,
      "vlan_id": 0,
      "pool_id": 0,
      "owner_id": 0,
      "owner_type": 0,
      "dhcp_options": [
        {
          "id": 1,
          "type": 1,
          "value": 100
        },
        {
          "id": 2,
          "type": 2,
          "value": "String value"
        },
        {
          "id": 3,
          "type": 3,
          "value": "1.2.3.4"
        },
        {
          "id": 4,
          "type": 4,
          "value": "FFA"
        },
        {
          "id": 5,
          "type": 5,
          "addresses": [
            "1.1.1.1"
          ]
        }
      ],
      "isg_attrs": [
        {
          "isg_attr_id": 1,
          "isg_attr_value": "ABC"
        }
      ]
    }
  ],
  "quotas_count": [
    {
      "tclass": 10,
      "traffic_quota": 100
    }
  ]
}


########################################################################################################################
########################################################################################################################
###################################### TASKS         ###################################################################
########################################################################################################################

######################## Get Tariff plans all
### Вот этой штукой можно добывать, и отдавать на фронт для выбора тарифа, а сейчас можно, просто по дефолту
### получать список, и выбирать первый попавшийся.
### Сейчас для эксперимента, можно выбрать айди 2
GET http://espd-utm5-app.cifra-k.ru:9080/api/tariffing/tariffs

### User/TariffLinks - Get tariff links ### как я помню, эту штуку вроде как не использую, дальше.
### хотя функционал довольно интересный
GET http://espd-utm5-app.cifra-k.ru:9080/api/users/tarifflinks?user_id=7&account_id=7

### User/TariffLinks - Get accounting periods
GET http://espd-utm5-app.cifra-k.ru:9080/api/tariffing/accounting_periods

######################## Create Tariff link to user
### User/TariffLinks - Post tariff link
### вот этой штукой мы привяжем тарифный план к пользователю. Да и тут тоже аккаунт необходим для пользователя.
### т.е. вот опять то самое место где необходим этот аккаут пользователя.
### Потому, что на пользователе может быть дофига всяких аккаунтов. Для чего это необходимо? "саа".
###
### Так, наконец!!!! этой штукой мы создаем таррифик линк
POST http://espd-utm5-app.cifra-k.ru:9080/api/users/tarifflinks
Content-Type: application/json

{
    "user_id": 17,
    "account_id": 18,
    "first_tariff_id": 2,
    "second_tariff_id": 0,
    "accounting_period_id": 2,
    "tariff_link_id": 0,
    "change_now": false
}



######################## Create service link for user
### User/ServiceLinks - Post iptraffic
### чую что вот этой штукой и необходимо создавать сервисные линки
## возможно это последний шаг в этой штукенции

POST http://espd-utm5-app.cifra-k.ru:9080/api/users/servicelinks/iptraffic
Content-Type: application/json

{
  "user_id": 36,
  "account_id": 37,
  "service_id": 6,
  "tplink_id": 33,
  "accounting_period_id": 2,
  "start_date": 0,
  "expire_date": 0,
  "policy_id": 1,
  "cost_coef": 1,
  "house_comment": "",
  "comment": "",
  "unabon": 0,
  "house_id": 0,
  "unprepay": 0,
  "ip_group": [
    {
      "ip": "192.168.2.2",
      "mask": 32,
      "mac": "",
      "login": "",
      "allowed_cid": "",
      "password": "",
      "pool_name": "",
      "flags": 0,
      "nfprovider_id": 0,
      "switch_id": 0,
      "port_id": 0,
      "vlan_id": 0,
      "pool_id": 0,
      "owner_id": 0,
      "owner_type": 0,
      "dhcp_options": [],
      "isg_attrs": []
    }
  ],
  "quotas_count": [
    {
      "tclass": 10,
      "traffic_quota": 100
    }
  ]
}




######################## Reports - Get report of traffic
### пробуем делаем, забираем отчет по трафику
###
GET http://espd-utm5-app.cifra-k.ru:9080/api/reports/traffic?start=0&end=1577826000&user_id=0&account_id=0&accounting_period_id=0&group_id=0&type=0
Authorization: session_id {{session_id}}
Content-Type: application/json

###
GET http://espd-utm5-app.cifra-k.ru:9080/api/reports/traffic?start=1593536400&end=1597640673&user_id=0&account_id=0&accounting_period_id=0&group_id=0&type=0
Authorization: session_id {{session_id}}
Content-Type: application/json

###
#GET http://espd-utm5-app.cifra-k.ru:9080/api/reports/users_log?start=0&end=1572555600&user_id=0&action_id=0
#GET http://espd-utm5-app.cifra-k.ru:9080/api/reports/users_log?start=0&end=1572555600&user_id=0&action_id=0
#GET http://espd-utm5-app.cifra-k.ru:9080/api/reports/traffic?start=18444&end=18475&user_id=0&account_id=0&accounting_period_id=0&group_id=0&type=0
Authorization: session_id {{session_id}}
Content-Type: application/json
