/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { BaseStationReq } from '../model/baseStationReq';
import { BaseStationRes } from '../model/baseStationRes';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class BaseStationControllerImplService {

    protected basePath = 'https://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * baseStation
     * 
     * @param baseStationId baseStationId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public baseStationUsingGET(baseStationId: number, observe?: 'body', reportProgress?: boolean): Observable<BaseStationRes>;
    public baseStationUsingGET(baseStationId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<BaseStationRes>>;
    public baseStationUsingGET(baseStationId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<BaseStationRes>>;
    public baseStationUsingGET(baseStationId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (baseStationId === null || baseStationId === undefined) {
            throw new Error('Required parameter baseStationId was null or undefined when calling baseStationUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<BaseStationRes>(`${this.basePath}/api/base-stations/${encodeURIComponent(String(baseStationId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * baseStations
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public baseStationsUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<BaseStationRes>>;
    public baseStationsUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<BaseStationRes>>>;
    public baseStationsUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<BaseStationRes>>>;
    public baseStationsUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<BaseStationRes>>(`${this.basePath}/api/base-stations`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * remove
     * 
     * @param baseStationId baseStationId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public removeUsingDELETE1(baseStationId: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public removeUsingDELETE1(baseStationId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public removeUsingDELETE1(baseStationId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public removeUsingDELETE1(baseStationId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (baseStationId === null || baseStationId === undefined) {
            throw new Error('Required parameter baseStationId was null or undefined when calling removeUsingDELETE1.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}/api/base-stations/${encodeURIComponent(String(baseStationId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * save
     * 
     * @param baseStation baseStation
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public saveUsingPOST(baseStation: BaseStationReq, observe?: 'body', reportProgress?: boolean): Observable<BaseStationRes>;
    public saveUsingPOST(baseStation: BaseStationReq, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<BaseStationRes>>;
    public saveUsingPOST(baseStation: BaseStationReq, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<BaseStationRes>>;
    public saveUsingPOST(baseStation: BaseStationReq, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (baseStation === null || baseStation === undefined) {
            throw new Error('Required parameter baseStation was null or undefined when calling saveUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<BaseStationRes>(`${this.basePath}/api/base-stations`,
            baseStation,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * update
     * 
     * @param baseStation baseStation
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateUsingPUT1(baseStation: BaseStationReq, observe?: 'body', reportProgress?: boolean): Observable<BaseStationRes>;
    public updateUsingPUT1(baseStation: BaseStationReq, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<BaseStationRes>>;
    public updateUsingPUT1(baseStation: BaseStationReq, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<BaseStationRes>>;
    public updateUsingPUT1(baseStation: BaseStationReq, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (baseStation === null || baseStation === undefined) {
            throw new Error('Required parameter baseStation was null or undefined when calling updateUsingPUT1.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<BaseStationRes>(`${this.basePath}/api/base-stations`,
            baseStation,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
