/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PointReq } from './pointReq';


export interface AccessPointNewDTO { 
    address?: string;
    amount?: number;
    billingId?: number;
    completed?: number;
    contractor?: string;
    customer?: string;
    declaredSpeed?: string;
    description?: string;
    ended?: string;
    governmentProgram?: number;
    hardware?: string;
    id?: number;
    internetAccess?: number;
    ipConfig?: string;
    maxAmount?: number;
    name?: string;
    node?: string;
    number?: string;
    operator?: number;
    point?: PointReq;
    quality?: string;
    software?: string;
    started?: string;
    state?: string;
    type?: string;
    ucn?: number;
    visible?: boolean;
}
