/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Operator } from './operator';
import { PointRes } from './pointRes';
import { TypeMobile } from './typeMobile';


export interface BaseStationRes { 
    actionDate?: Date;
    address?: string;
    coverageRadius?: number;
    id?: number;
    mobileType?: TypeMobile;
    operator?: Operator;
    point?: PointRes;
    propHeight?: number;
}
