/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ExtZabbixDto { 
    groupid?: string;
    hostName?: string;
    ip?: string;
    macro?: string;
    macroValue?: string;
    tag?: string;
    tagValue?: string;
    templateid?: string;
}
