/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LocationFeature } from './locationFeature';


export interface FeatureEditFull { 
    action?: FeatureEditFull.ActionEnum;
    id?: number;
    newValue?: LocationFeature;
    tc?: LocationFeature;
}
export namespace FeatureEditFull {
    export type ActionEnum = 'CREATE' | 'DELETE' | 'UPDATE';
    export const ActionEnum = {
        CREATE: 'CREATE' as ActionEnum,
        DELETE: 'DELETE' as ActionEnum,
        UPDATE: 'UPDATE' as ActionEnum
    };
}
