/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LocationReq } from './locationReq';
import { MultiPolygonReq } from './multiPolygonReq';
import { PointReq } from './pointReq';


export interface GeoDataReq { 
    administrativeCenter?: PointReq;
    fias?: string;
    geometry?: MultiPolygonReq;
    id?: number;
    locations?: Array<LocationReq>;
    okato?: string;
    oktmo?: string;
    osmId?: string;
}
