/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LocationRes } from './locationRes';
import { MultiPolygonRes } from './multiPolygonRes';
import { PointRes } from './pointRes';


export interface GeoDataRes { 
    administrativeCenter?: PointRes;
    fias?: string;
    geometry?: MultiPolygonRes;
    id?: number;
    locations?: Array<LocationRes>;
    okato?: string;
    oktmo?: string;
    osmId?: string;
}
