/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Location } from './location';
import { MultiPolygon } from './multiPolygon';
import { Point } from './point';


export interface GeoData { 
    administrativeCenter?: Point;
    fias?: string;
    geometry?: MultiPolygon;
    id?: number;
    locations?: Array<Location>;
    okato?: string;
    oktmo?: string;
    osmId?: string;
}
