/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GeoDataRes } from './geoDataRes';
import { OrganizationRes } from './organizationRes';
import { TechnicalCapabilityRes } from './technicalCapabilityRes';


export interface LocationRes { 
    children?: Array<LocationRes>;
    fias?: string;
    geoData?: GeoDataRes;
    id?: number;
    level?: number;
    name?: string;
    okato?: string;
    oktmo?: string;
    organizations?: Array<OrganizationRes>;
    parent?: LocationRes;
    population?: number;
    technicalCapabilities?: Array<TechnicalCapabilityRes>;
    type?: string;
}
