/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FeatureEditFull } from './featureEditFull';
import { LocationForTable } from './locationForTable';
import { User } from './user';


export interface LocationFeaturesEditingRequestFull { 
    comment?: string;
    created?: Date;
    createdBy?: string;
    declineComment?: string;
    featureEdits?: Array<FeatureEditFull>;
    id?: number;
    location?: LocationForTable;
    modified?: Date;
    modifiedBy?: string;
    status?: LocationFeaturesEditingRequestFull.StatusEnum;
    user?: User;
}
export namespace LocationFeaturesEditingRequestFull {
    export type StatusEnum = 'ACCEPTED' | 'DECLINED' | 'WAIT_FOR_STATE_TO_BE_SET';
    export const StatusEnum = {
        ACCEPTED: 'ACCEPTED' as StatusEnum,
        DECLINED: 'DECLINED' as StatusEnum,
        WAITFORSTATETOBESET: 'WAIT_FOR_STATE_TO_BE_SET' as StatusEnum
    };
}
