/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MultiPolygon } from './multiPolygon';


export interface LocationAreaBorders { 
    fullName?: string;
    geometry?: MultiPolygon;
    id?: number;
    name?: string;
    type?: string;
}
