/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface LocationSimpleFilterDTO { 
    fullName?: string;
    id?: number;
    name?: string;
    parent?: string;
    population?: number;
    type?: string;
}
