/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FeatureProvidingInfo } from './featureProvidingInfo';


export interface LocationProvidingInfo { 
    ats?: FeatureProvidingInfo;
    cellular?: FeatureProvidingInfo;
    infomat?: FeatureProvidingInfo;
    internet?: FeatureProvidingInfo;
    locationsCount?: number;
    name?: string;
    payphone?: FeatureProvidingInfo;
    population?: number;
    post?: FeatureProvidingInfo;
    radio?: FeatureProvidingInfo;
    tv?: FeatureProvidingInfo;
    type?: string;
}
