/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GovernmentDevelopmentProgram } from './governmentDevelopmentProgram';
import { Operator } from './operator';
import { Signal } from './signal';
import { TypeMobile } from './typeMobile';
import { TypePost } from './typePost';
import { TypeTrunkChannel } from './typeTrunkChannel';


export interface LocationFeature { 
    govYearComplete?: number;
    governmentDevelopmentProgram?: GovernmentDevelopmentProgram;
    id?: number;
    locationId?: number;
    operator?: Operator;
    payphones: number;
    quality?: LocationFeature.QualityEnum;
    state?: LocationFeature.StateEnum;
    trunkChannel?: TypeTrunkChannel;
    tvOrRadioTypes?: Array<Signal>;
    type?: LocationFeature.TypeEnum;
    typeMobile?: TypeMobile;
    typePost?: TypePost;
}
export namespace LocationFeature {
    export type QualityEnum = 'ABSENT' | 'GOOD' | 'NORMAL';
    export const QualityEnum = {
        ABSENT: 'ABSENT' as QualityEnum,
        GOOD: 'GOOD' as QualityEnum,
        NORMAL: 'NORMAL' as QualityEnum
    };
    export type StateEnum = 'ACTIVE' | 'ARCHIVE' | 'PLAN' | 'PLAN1YEAR' | 'PLAN2YEAR' | 'WAIT_FOR_STATE_TO_BE_SET';
    export const StateEnum = {
        ACTIVE: 'ACTIVE' as StateEnum,
        ARCHIVE: 'ARCHIVE' as StateEnum,
        PLAN: 'PLAN' as StateEnum,
        PLAN1YEAR: 'PLAN1YEAR' as StateEnum,
        PLAN2YEAR: 'PLAN2YEAR' as StateEnum,
        WAITFORSTATETOBESET: 'WAIT_FOR_STATE_TO_BE_SET' as StateEnum
    };
    export type TypeEnum = 'ATS' | 'INET' | 'INFOMAT' | 'MOBILE' | 'PAYPHONE' | 'POST' | 'RADIO' | 'TV';
    export const TypeEnum = {
        ATS: 'ATS' as TypeEnum,
        INET: 'INET' as TypeEnum,
        INFOMAT: 'INFOMAT' as TypeEnum,
        MOBILE: 'MOBILE' as TypeEnum,
        PAYPHONE: 'PAYPHONE' as TypeEnum,
        POST: 'POST' as TypeEnum,
        RADIO: 'RADIO' as TypeEnum,
        TV: 'TV' as TypeEnum
    };
}
