/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GeoData } from './geoData';
import { Organization } from './organization';
import { TechnicalCapability } from './technicalCapability';


export interface Location { 
    children?: Array<Location>;
    fias?: string;
    geoData?: GeoData;
    id?: number;
    level?: number;
    name?: string;
    okato?: string;
    oktmo?: string;
    organizations?: Array<Organization>;
    parent?: Location;
    population?: number;
    technicalCapabilities?: Array<TechnicalCapability>;
    type?: string;
}
