/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LocationParent } from './locationParent';
import { OrganizationForLocationTable } from './organizationForLocationTable';
import { TechnicalCapabilityForLocationTable } from './technicalCapabilityForLocationTable';


export interface LocationForTable { 
    children?: Array<LocationForTable>;
    id?: number;
    locationParent?: LocationParent;
    name?: string;
    organizations?: Array<OrganizationForLocationTable>;
    population?: number;
    technicalCapabilities?: Array<TechnicalCapabilityForLocationTable>;
    type?: string;
}
