/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GeoDataReq } from './geoDataReq';
import { OrganizationReq } from './organizationReq';
import { TechnicalCapabilityReq } from './technicalCapabilityReq';


export interface LocationReq { 
    children?: Array<LocationReq>;
    fias?: string;
    geoData?: GeoDataReq;
    id?: number;
    level?: number;
    name?: string;
    okato?: string;
    oktmo?: string;
    organizations?: Array<OrganizationReq>;
    parent?: LocationReq;
    population?: number;
    technicalCapabilities?: Array<TechnicalCapabilityReq>;
    type?: string;
}
