/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LocationFeature } from './locationFeature';
import { LocationParent } from './locationParent';


export interface LocationFC { 
    id?: number;
    locationParent?: LocationParent;
    name?: string;
    okato?: string;
    population?: number;
    technicalCapabilities?: Array<LocationFeature>;
    type?: string;
}
