/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Geometry } from './geometry';


export interface MapAccessPoint { 
    connectionState?: MapAccessPoint.ConnectionStateEnum;
    id?: number;
    point?: Geometry;
}
export namespace MapAccessPoint {
    export type ConnectionStateEnum = 'ACTIVE' | 'DISABLED' | 'NOT_MONITORED';
    export const ConnectionStateEnum = {
        ACTIVE: 'ACTIVE' as ConnectionStateEnum,
        DISABLED: 'DISABLED' as ConnectionStateEnum,
        NOTMONITORED: 'NOT_MONITORED' as ConnectionStateEnum
    };
}
