/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GeoDataShortReq } from './geoDataShortReq';
import { LocationParent } from './locationParent';


export interface MapLocationReq { 
    fias?: string;
    geoData?: GeoDataShortReq;
    id?: number;
    name?: string;
    parent?: LocationParent;
    type?: string;
}
