/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Coordinate } from './coordinate';
import { EnvelopeRes } from './envelopeRes';
import { Geometry } from './geometry';
import { GeometryFactoryRes } from './geometryFactoryRes';
import { PointRes } from './pointRes';
import { PrecisionModelRes } from './precisionModelRes';


export interface MultiPolygonRes { 
    area?: number;
    boundary?: Geometry;
    boundaryDimension?: number;
    centroid?: PointRes;
    coordinate?: Coordinate;
    coordinates?: Array<Coordinate>;
    dimension?: number;
    empty?: boolean;
    envelope?: Geometry;
    envelopeInternal?: EnvelopeRes;
    factory?: GeometryFactoryRes;
    geometryType?: string;
    interiorPoint?: PointRes;
    length?: number;
    numGeometries?: number;
    numPoints?: number;
    precisionModel?: PrecisionModelRes;
    rectangle?: boolean;
    simple?: boolean;
    srid?: number;
    userData?: any;
    valid?: boolean;
}
