/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccessPointReq } from './accessPointReq';
import { LocationReq } from './locationReq';
import { TypeOrganization } from './typeOrganization';
import { TypeSmo } from './typeSmo';


export interface OrganizationReq { 
    accessPoints?: Array<AccessPointReq>;
    acronym?: string;
    address?: string;
    children?: Array<OrganizationReq>;
    fias?: string;
    id?: number;
    inn?: string;
    kpp?: string;
    location?: LocationReq;
    name?: string;
    parent?: OrganizationReq;
    smo?: TypeSmo;
    type?: TypeOrganization;
}
