/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface OrganizationShortDTO { 
    acronym?: string;
    address?: string;
    fias?: string;
    id?: number;
    inn?: string;
    kpp?: string;
    location?: number;
    name?: string;
    parent?: number;
    smo?: number;
    type?: number;
}
