/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccessPointRes } from './accessPointRes';
import { LocationRes } from './locationRes';
import { TypeOrganization } from './typeOrganization';
import { TypeSmo } from './typeSmo';


export interface OrganizationRes { 
    accessPoints?: Array<AccessPointRes>;
    acronym?: string;
    address?: string;
    children?: Array<OrganizationRes>;
    fias?: string;
    id?: number;
    inn?: string;
    kpp?: string;
    location?: LocationRes;
    name?: string;
    parent?: OrganizationRes;
    smo?: TypeSmo;
    type?: TypeOrganization;
}
