/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ReportOrganizationDTO } from './reportOrganizationDTO';


export interface PaginatedListReportOrganizationDTO { 
    count?: number;
    next?: string;
    previous?: string;
    results?: Array<ReportOrganizationDTO>;
}
