/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Type } from './type';


export interface PrecisionModel { 
    floating?: boolean;
    maximumSignificantDigits?: number;
    offsetX?: number;
    offsetY?: number;
    scale?: number;
    type?: Type;
}
