/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LocationDTO } from './locationDTO';
import { TypeOrgDTO } from './typeOrgDTO';
import { TypeSmoDTO } from './typeSmoDTO';


export interface ReportOrganizationDTO { 
    id?: number;
    location?: LocationDTO;
    name?: string;
    smo?: TypeSmoDTO;
    type?: TypeOrgDTO;
}
