/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ReportOrganizationDTO } from './reportOrganizationDTO';
import { TypeInternetAccessDTO } from './typeInternetAccessDTO';


export interface ReportApContractDTO { 
    address?: string;
    amount?: number;
    contractor?: string;
    declaredSpeed?: string;
    id?: number;
    internetAccess?: TypeInternetAccessDTO;
    number?: string;
    organization?: ReportOrganizationDTO;
    type?: string;
}
