/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GovernmentDevelopmentProgram } from './governmentDevelopmentProgram';
import { LocationRes } from './locationRes';
import { Operator } from './operator';


export interface TechnicalCapabilityRes { 
    createdBy?: string;
    createdDate?: Date;
    govProgram?: GovernmentDevelopmentProgram;
    govStatus?: TechnicalCapabilityRes.GovStatusEnum;
    govYearComplete?: number;
    id?: number;
    location?: LocationRes;
    modifiedBy?: string;
    modifiedDate?: Date;
    operator?: Operator;
    quality?: TechnicalCapabilityRes.QualityEnum;
    state?: TechnicalCapabilityRes.StateEnum;
}
export namespace TechnicalCapabilityRes {
    export type GovStatusEnum = 'DONE' | 'NONE' | 'PLAN';
    export const GovStatusEnum = {
        DONE: 'DONE' as GovStatusEnum,
        NONE: 'NONE' as GovStatusEnum,
        PLAN: 'PLAN' as GovStatusEnum
    };
    export type QualityEnum = 'ABSENT' | 'GOOD' | 'NORMAL';
    export const QualityEnum = {
        ABSENT: 'ABSENT' as QualityEnum,
        GOOD: 'GOOD' as QualityEnum,
        NORMAL: 'NORMAL' as QualityEnum
    };
    export type StateEnum = 'ACTIVE' | 'ARCHIVE' | 'PLAN' | 'PLAN1YEAR' | 'PLAN2YEAR' | 'WAIT_FOR_STATE_TO_BE_SET';
    export const StateEnum = {
        ACTIVE: 'ACTIVE' as StateEnum,
        ARCHIVE: 'ARCHIVE' as StateEnum,
        PLAN: 'PLAN' as StateEnum,
        PLAN1YEAR: 'PLAN1YEAR' as StateEnum,
        PLAN2YEAR: 'PLAN2YEAR' as StateEnum,
        WAITFORSTATETOBESET: 'WAIT_FOR_STATE_TO_BE_SET' as StateEnum
    };
}
