/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GovernmentDevelopmentProgram } from './governmentDevelopmentProgram';
import { Signal } from './signal';
import { TypeMobile } from './typeMobile';
import { TypePost } from './typePost';
import { TypeTrunkChannel } from './typeTrunkChannel';


export interface TechnicalCapabilityForLocationTable { 
    govYearComplete?: number;
    governmentDevelopmentProgram?: GovernmentDevelopmentProgram;
    id?: number;
    locationId?: number;
    operatorId?: number;
    payphones?: number;
    quality?: TechnicalCapabilityForLocationTable.QualityEnum;
    state?: TechnicalCapabilityForLocationTable.StateEnum;
    trunkChannel?: TypeTrunkChannel;
    tvOrRadioTypes?: Array<Signal>;
    type?: string;
    typeMobile?: TypeMobile;
    typePost?: TypePost;
}
export namespace TechnicalCapabilityForLocationTable {
    export type QualityEnum = 'ABSENT' | 'GOOD' | 'NORMAL';
    export const QualityEnum = {
        ABSENT: 'ABSENT' as QualityEnum,
        GOOD: 'GOOD' as QualityEnum,
        NORMAL: 'NORMAL' as QualityEnum
    };
    export type StateEnum = 'ACTIVE' | 'ARCHIVE' | 'PLAN' | 'PLAN1YEAR' | 'PLAN2YEAR' | 'WAIT_FOR_STATE_TO_BE_SET';
    export const StateEnum = {
        ACTIVE: 'ACTIVE' as StateEnum,
        ARCHIVE: 'ARCHIVE' as StateEnum,
        PLAN: 'PLAN' as StateEnum,
        PLAN1YEAR: 'PLAN1YEAR' as StateEnum,
        PLAN2YEAR: 'PLAN2YEAR' as StateEnum,
        WAITFORSTATETOBESET: 'WAIT_FOR_STATE_TO_BE_SET' as StateEnum
    };
}
