/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GovernmentDevelopmentProgram } from './governmentDevelopmentProgram';
import { MapLocationReq } from './mapLocationReq';
import { Operator } from './operator';
import { TypeTrunkChannel } from './typeTrunkChannel';


export interface TrunkChannelReq { 
    commissioning?: string;
    completed?: number;
    decommissioning?: string;
    id?: number;
    locationEnd?: MapLocationReq;
    locationStart?: MapLocationReq;
    operator?: Operator;
    program?: GovernmentDevelopmentProgram;
    typeTrunkChannel?: TypeTrunkChannel;
}
