/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Location } from './location';


export interface User { 
    email?: string;
    firstName?: string;
    id?: number;
    lastName?: string;
    location?: string;
    locations?: Array<Location>;
    oid?: number;
    patronymicName?: string;
    roles?: Array<User.RolesEnum>;
    username?: string;
}
export namespace User {
    export type RolesEnum = 'ADMIN' | 'GUEST' | 'MUNICIPALITY' | 'OPERATOR' | 'ORGANIZATION';
    export const RolesEnum = {
        ADMIN: 'ADMIN' as RolesEnum,
        GUEST: 'GUEST' as RolesEnum,
        MUNICIPALITY: 'MUNICIPALITY' as RolesEnum,
        OPERATOR: 'OPERATOR' as RolesEnum,
        ORGANIZATION: 'ORGANIZATION' as RolesEnum
    };
}
